### ISSUE TITLE
Corundum to-do list

### ISSUE THREAD

**Issue by alexforencich** [corundum/corundum#100]
Core logic:

- [ ] MSI-X
- [ ] RISC-V management core
- [ ] Variable-length descriptor support
- [ ] Clock information block

Device support:

- [ ] Arria 10 PCIe gen 3 x8
- [ ] Stratix 10 GX/MX PCIe gen 3 x16
- [ ] Stratix 10 DX PCIe gen 3 x8
- [ ] Stratix 10 DX PCIe gen 3 x16
- [ ] Stratix 10 DX PCIe gen 4 x16
- [ ] Agilex PCIe gen 3 x8
- [ ] Agilex PCIe gen 3 x16
- [ ] Agilex PCIe gen 4 x16
- [ ] US+ 256 PCIe tags
- [ ] US/US+ segmented RC/RQ

Driver:

- [ ] RX page reuse
- [ ] RX scatter/gather
